application: oinopaponton
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  upload: public/index.html
  static_files: public/index.html

- url: /(.*)
  upload: public/(.*)
  static_files: public/\1
