source "https://rubygems.org"

gem "bourbon"
gem "kramdown"
gem "middleman"
gem "middleman-autoprefixer"
gem "middleman-blog"
gem "middleman-deploy", "= 2.0.0.pre.alpha"
gem "middleman-livereload"
gem "middleman-sprockets"
gem "neat"
gem "sassc"
